In [1]:
import pandas as pd

data = {
    'Date': [
        '2020-03-13 08-PM',
        '2020-03-13 07-PM',
        '2020-03-13 06-PM',
        '2020-03-13 05-PM',
        '2020-03-13 04-PM'
    ],
    'Symbol': [
        'ETHUSD',
        'ETHUSD',
        'ETHUSD',
        'ETHUSD',
        'ETHUSD'
    ],
    'Open': [
        129.94,
        119.51,
        124.47,
        124.08,
        124.85
    ],
    'High': [
        131.82,
        132.02,
        124.85,
        127.42,
        129.51
    ],
    'Low': [
        126.87,
        117.10,
        115.50,
        121.63,
        120.17
    ],
    'Close': [
        128.71,
        129.94,
        119.51,
        124.47,
        124.08
    ],
    'Volume': [
        1940673.93,
        7579741.09,
        4898735.81,
        2753450.92,
        4461424.71
    ]
}

df = pd.DataFrame(data)

print(df)

               Date  Symbol    Open    High     Low   Close      Volume
0  2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1  2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2  2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3  2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4  2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71

In [2]:
df.shape

(5, 7)

In [4]:
df.loc[0, 'Date']

'2020-03-13 08-PM'

In [6]:
# df['Date'] = pd.to_datetime(df['Date']) (not formatted)

In [7]:
df['Date'] = pd.to_datetime(df['Date'], format = '%Y-%m-%d %I-%p')

In [8]:
df['Date']

0   2020-03-13 20:00:00
1   2020-03-13 19:00:00
2   2020-03-13 18:00:00
3   2020-03-13 17:00:00
4   2020-03-13 16:00:00
Name: Date, dtype: datetime64[us]

In [9]:
df.loc[0,'Date'].day_name()

'Friday'

In [11]:
# for CSV files in in brackets, "parse_dates=['Date'],date parser = d_parser"
# d_parser = lambda x:pd.datetime.strptime(x, ''%Y-%m-%d %I-%p')

In [13]:
df['Date'].dt.day_name()

0    Friday
1    Friday
2    Friday
3    Friday
4    Friday
Name: Date, dtype: str

In [14]:
df['DayOfWeek'] = df['Date'].dt.day_name()

In [15]:
df

,Date,Symbol,Open,High,Low,Close,Volume,DayOfWeek
0,2020-03-13 20:00:00,ETHUSD,129.94,131.82,126.87,128.71,1940673.93,Friday
1,2020-03-13 19:00:00,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,Friday
2,2020-03-13 18:00:00,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,Friday
3,2020-03-13 17:00:00,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,Friday
4,2020-03-13 16:00:00,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,Friday

In [16]:
df['Date'].min()

Timestamp('2020-03-13 16:00:00')

In [17]:
df['Date'].max()

Timestamp('2020-03-13 20:00:00')

In [18]:
df['Date'].max() - df['Date'].min()

Timedelta('0 days 04:00:00')

In [19]:
# This difference is called Time Delta

In [24]:
df['Date'] = pd.to_datetime(df['Date'])

filt = (df['Date'] >= pd.Timestamp('2019-01-01')) & \
       (df['Date'] < pd.Timestamp('2020-01-01'))

df.loc[filt]

Empty DataFrame
Columns: [Date, Symbol, Open, High, Low, Close, Volume, DayOfWeek]
Index: []

In [26]:
df.set_index('Date',inplace = True)

In [27]:
df

,Symbol,Open,High,Low,Close,Volume,DayOfWeek
Date,,,,,,,
2020-03-13 20:00:00,ETHUSD,129.94,131.82,126.87,128.71,1940673.93,Friday
2020-03-13 19:00:00,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,Friday
2020-03-13 18:00:00,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,Friday
2020-03-13 17:00:00,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,Friday
2020-03-13 16:00:00,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,Friday

In [29]:
# df['2020']

In [31]:
# df['2020-01' : '2020-02']  is slicing

In [32]:
# df['2020-01' : '2020-02']['Close'].mean()

In [35]:
# df['2020-01-01']['High'].max()

In [40]:
highs = df['High'].resample('D').max()       # 'D' can be replaced for Week(W),Month(M)....
highs

Date
2020-03-13    132.02
Freq: D, Name: High, dtype: float64

In [39]:
# %matplotlib inline

In [41]:
# highs.plot()

In [43]:
# resample and use multiple columns
# df.resample('W').mean()

In [44]:
# df.resample('W').agg({'Close': 'mean','High': 'max'})