In [1]:
import pandas as pd
import numpy as np

people = {
    'first': ['Corey', 'Jane', 'John', 'Chris', np.nan, None, 'NA'],
    'last': ['Schafer', 'Doe', 'Doe', 'Schafer', np.nan, np.nan, 'Missing'],
    'email': [
        'CoreyMSchafer@gmail.com',
        'JaneDoe@email.com',
        'JohnDoe@email.com',
        None,
        np.nan,
        'Anonymous@email.com',
        'NA'
    ],
    'age': ['33', '55', '63', '36', None, None, 'Missing']
}

df = pd.DataFrame(people)
df.replace('NA', np.nan, inplace=True)
df.replace('Missing', np.nan, inplace=True)

df

   first     last                    email  age
0  Corey  Schafer  CoreyMSchafer@gmail.com   33
1   Jane      Doe        JaneDoe@email.com   55
2   John      Doe        JohnDoe@email.com   63
3  Chris  Schafer                      NaN   36
4    NaN      NaN                      NaN  NaN
5    NaN      NaN      Anonymous@email.com  NaN
6    NaN      NaN                      NaN  NaN

In [2]:
df.dropna() #drops NaN values (except custom missing values at last)

   first     last                    email age
0  Corey  Schafer  CoreyMSchafer@gmail.com  33
1   Jane      Doe        JaneDoe@email.com  55
2   John      Doe        JohnDoe@email.com  63

In [3]:
df.dropna(axis='index',how='all') # how -> any means '|' and all means '&'

   first     last                    email  age
0  Corey  Schafer  CoreyMSchafer@gmail.com   33
1   Jane      Doe        JaneDoe@email.com   55
2   John      Doe        JohnDoe@email.com   63
3  Chris  Schafer                      NaN   36
5    NaN      NaN      Anonymous@email.com  NaN

In [4]:
df.dropna(axis='columns',how='all')

   first     last                    email  age
0  Corey  Schafer  CoreyMSchafer@gmail.com   33
1   Jane      Doe        JaneDoe@email.com   55
2   John      Doe        JohnDoe@email.com   63
3  Chris  Schafer                      NaN   36
4    NaN      NaN                      NaN  NaN
5    NaN      NaN      Anonymous@email.com  NaN
6    NaN      NaN                      NaN  NaN

In [5]:
df.dropna(axis='index',how='any', subset = ['email'])

   first     last                    email  age
0  Corey  Schafer  CoreyMSchafer@gmail.com   33
1   Jane      Doe        JaneDoe@email.com   55
2   John      Doe        JohnDoe@email.com   63
5    NaN      NaN      Anonymous@email.com  NaN

In [6]:
df.isna() #mask for NaN values

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False   True  False
4   True   True   True   True
5   True   True  False   True
6   True   True   True   True

In [7]:
df.fillna('MISSING!')

      first      last                    email       age
0     Corey   Schafer  CoreyMSchafer@gmail.com        33
1      Jane       Doe        JaneDoe@email.com        55
2      John       Doe        JohnDoe@email.com        63
3     Chris   Schafer                 MISSING!        36
4  MISSING!  MISSING!                 MISSING!  MISSING!
5  MISSING!  MISSING!      Anonymous@email.com  MISSING!
6  MISSING!  MISSING!                 MISSING!  MISSING!

In [8]:
df.dtypes

first    str
last     str
email    str
age      str
dtype: object

In [ ]:
# When we have NaN values in a series which needs to be str->int, use float as NaN-> Float under the hood

In [9]:
type(np.nan)

float

In [ ]:
# df['age'] = df['age'].astype(int) casts str to int but will not work here due to reason above

In [10]:
df['age'] = df['age'].astype(float)

In [11]:
df.dtypes

first        str
last         str
email        str
age      float64
dtype: object

In [12]:
df['age'].mean()

np.float64(46.75)

In [ ]:
 # df.astype() for casting whole df